//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string msgID { get; set; }
        public string senderID { get; set; }
        public string receiverID { get; set; }
        public string msgContent { get; set; }
        public System.DateTime msgTime { get; set; }
        public bool msgStatus { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
