//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static DeWay.Models.Metadata;

    [MetadataType(typeof(MetadataRefund))]
    public partial class Refund
    {
        public string rfdID { get; set; }
        public string odrID { get; set; }
        public Nullable<decimal> rfdShip { get; set; }
        public string rfdReason { get; set; }
        public bool rfdProduct { get; set; }
        public bool rfdShipping { get; set; }
        public System.DateTime rfdDate { get; set; }
        public string rfdStatusID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual RefundStatus RefundStatus { get; set; }
        public virtual RefundAccount RefundAccount { get; set; }
    }
}
