//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shopDBEntities : DbContext
    {
        public shopDBEntities()
            : base("name=shopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actBulletin> actBulletin { get; set; }
        public virtual DbSet<Adm> Adm { get; set; }
        public virtual DbSet<AdmAccount> AdmAccount { get; set; }
        public virtual DbSet<Cart_OrderDetail> Cart_OrderDetail { get; set; }
        public virtual DbSet<FavoSeller> FavoSeller { get; set; }
        public virtual DbSet<FirstLayer> FirstLayer { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberAccount> MemberAccount { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<ntfCategory> ntfCategory { get; set; }
        public virtual DbSet<ntfRecord> ntfRecord { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductImage> ProductImage { get; set; }
        public virtual DbSet<QA> QA { get; set; }
        public virtual DbSet<Refund> Refund { get; set; }
        public virtual DbSet<RefundAccount> RefundAccount { get; set; }
        public virtual DbSet<RefundStatus> RefundStatus { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<rptRecord> rptRecord { get; set; }
        public virtual DbSet<SecondLayer> SecondLayer { get; set; }
        public virtual DbSet<Seller> Seller { get; set; }
        public virtual DbSet<SellerAut> SellerAut { get; set; }
        public virtual DbSet<SellerPhone> SellerPhone { get; set; }
        public virtual DbSet<Shipper> Shipper { get; set; }
        public virtual DbSet<ShipperDetail> ShipperDetail { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<ThirdLayer> ThirdLayer { get; set; }
        public virtual DbSet<WishList> WishList { get; set; }
    }
}
